/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaOat;

/**
 *
 * @author 104dk
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneTFundo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMenu = new javax.swing.JMenu();
        jMenuItemCadastrar = new javax.swing.JMenuItem();
        jMenuItemConsultar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaPrincipal");
        setMaximumSize(new java.awt.Dimension(560, 364));
        setMinimumSize(new java.awt.Dimension(560, 364));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPaneTFundo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDesktopPaneTFundoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jDesktopPaneTFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 560));

        jMenuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao-home.png"))); // NOI18N
        jMenuMenu.setText("Menu");
        jMenuMenu.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jMenuMenu.setMaximumSize(new java.awt.Dimension(87, 30));

        jMenuItemCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar-ficheiro25x25.png"))); // NOI18N
        jMenuItemCadastrar.setText("Cadastrar");
        jMenuItemCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItemCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItemCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemCadastrar);

        jMenuItemConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/busca+Lupa25x25.png"))); // NOI18N
        jMenuItemConsultar.setText("Editar Cadastro");
        jMenuItemConsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItemConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemConsultar);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/barra-de-menu25x25.png"))); // NOI18N
        jMenuItem3.setText("Exluir Cadastro");
        jMenuMenu.add(jMenuItem3);

        jMenuBar1.add(jMenuMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/chave-inglesa - Copia.png"))); // NOI18N
        jMenu1.setText("Ajuda");
        jMenu1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(89, 30));

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ajuda25x25.png"))); // NOI18N
        jMenuItem2.setText("Suporte");
        jMenuItem2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login 35x35.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.setAutoscrolls(true);
        jMenuSair.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jMenuSair.setMaximumSize(new java.awt.Dimension(81, 30));
        jMenuSair.setMinimumSize(new java.awt.Dimension(81, 30));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItem1);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarActionPerformed
        TCad tela = new TCad();
        jDesktopPaneTFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarActionPerformed

    private void jMenuItemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarActionPerformed
        TConsultar tela = new TConsultar();
        jDesktopPaneTFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarActionPerformed

    private void jDesktopPaneTFundoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDesktopPaneTFundoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPaneTFundoAncestorAdded

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible (true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneTFundo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemCadastrar;
    private javax.swing.JMenuItem jMenuItemConsultar;
    private javax.swing.JMenu jMenuMenu;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
